### ISSUE TITLE
Go no longer supporting get outside a module

### ISSUE THREAD

**Issue by PeterGerma** [MrIceman/go-uml#1]
go: go.mod file not found in current directory or any parent directory.
        'go get' is no longer supported outside a module.
        To build and install a command, use 'go install' with a version,
        like 'go install example.com/cmd@latest'
        For more information, see https://golang.org/doc/go-get-install-deprecation
        or run 'go help get' or 'go help install'.

**Comment by MrIceman** [comment]
Hi @PeterGerma , it seems like you are running
`go get -u github.com/mriceman/go-uml` outside of a go project that has a ` go.mod` file.
just make sure you have a go project initialized, in this case run first
`go mod init <go-project>`

**Comment by MrIceman** [comment]
@PeterGerma since I haven't heard anything from you yet, I assume the issue is solved therefore I am going to close this issue. Feel free to open another one in case
